/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sellers/{sellerId}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 판매자 연동 정보 조회 */
        get: operations["get"];
        /** 판매자 연동 정보 저장 또는 갱신 */
        put: operations["upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 판매자 생성 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/insights/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 특정 날짜 인사이트 생성 */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/import-jobs/orders/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 주문 CSV 업로드 및 동기 적재 */
        post: operations["importOrdersCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/daily-metrics/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 일별 지표 수동 집계 실행 */
        post: operations["aggregate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 네이버 커머스 SELLER 액세스 토큰 발급 */
        post: operations["issueSellerToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sample-data/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 기존 데이터를 초기화하고 샘플 데이터를 주입 */
        post: operations["bootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pipelines/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 전체 판매자 대상 일별 집계 및 인사이트 생성 실행 */
        post: operations["runDailyPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 판매자 단건 조회 */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 특정 날짜 인사이트 조회 */
        get: operations["getByDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/insights/{insightId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 인사이트 상세 조회 */
        get: operations["getInsight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/import-jobs/{importJobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 가져오기 작업 단건 조회 */
        get: operations["getImportJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 판매자 대시보드 조회 */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/dashboard/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 대시보드용 일별 지표 범위 조회 */
        get: operations["getMetricRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/dashboard/insights/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 대시보드용 최근 인사이트 조회 */
        get: operations["getRecentInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sellers/{sellerId}/daily-metrics/{metricDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 일별 지표 단건 조회 */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 애플리케이션 및 DB 상태 조회 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pipelines/daily/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 일별 파이프라인 실행 이력 목록 조회 */
        get: operations["getRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pipelines/daily/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 일별 파이프라인 실행 이력 상세 조회 */
        get: operations["getRunDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pipelines/daily/locks/{metricDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 특정 날짜 파이프라인 실행 lock 강제 해제 */
        delete: operations["forceReleaseLock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpsertSellerCredentialRequest: {
            clientId: string;
            clientSecret: string;
        };
        ApiResponseSellerCredentialResponse: {
            success?: boolean;
            data?: components["schemas"]["SellerCredentialResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        ErrorResponse: {
            code?: string;
            message?: string;
            details?: {
                [key: string]: string;
            };
            /** Format: date-time */
            timestamp?: string;
        };
        SellerCredentialResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sellerId?: number;
            clientId?: string;
            clientSecretMasked?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateSellerRequest: {
            externalSellerId: string;
            sellerName: string;
        };
        ApiResponseSellerResponse: {
            success?: boolean;
            data?: components["schemas"]["SellerResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        SellerResponse: {
            /** Format: int64 */
            id?: number;
            externalSellerId?: string;
            sellerName?: string;
            /** @enum {string} */
            status?: "CONNECTED" | "DISCONNECTED";
            /** Format: date-time */
            connectedAt?: string;
            /** Format: date-time */
            lastSyncedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseInsightsByDateResponse: {
            success?: boolean;
            data?: components["schemas"]["InsightsByDateResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        InsightResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sellerId?: number;
            /** Format: date */
            metricDate?: string;
            /** @enum {string} */
            insightType?: "ORDER_DROP" | "SOLD_OUT_RISK" | "NO_ORDER" | "STALE_PRODUCT_RISK" | "AVERAGE_ORDER_AMOUNT_DROP";
            /** @enum {string} */
            severity?: "LOW" | "MEDIUM" | "HIGH";
            title?: string;
            summary?: string;
            evidenceJson?: string;
            generatedBy?: string;
            recommendations?: components["schemas"]["RecommendationResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        InsightsByDateResponse: {
            /** Format: int64 */
            sellerId?: number;
            /** Format: date */
            metricDate?: string;
            /** Format: int32 */
            insightCount?: number;
            insights?: components["schemas"]["InsightResponse"][];
        };
        RecommendationResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            priority?: number;
            actionCode?: string;
            actionTitle?: string;
            actionMessage?: string;
            sourceRule?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseImportJobResponse: {
            success?: boolean;
            data?: components["schemas"]["ImportJobResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        ImportJobResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sellerId?: number;
            /** @enum {string} */
            importType?: "ORDER_CSV";
            /** @enum {string} */
            status?: "PENDING" | "PROCESSING" | "SUCCESS" | "FAILED";
            originalFileName?: string;
            /** Format: int32 */
            totalRowCount?: number;
            /** Format: int32 */
            successRowCount?: number;
            /** Format: int32 */
            failedRowCount?: number;
            errorMessage?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseDailyMetricResponse: {
            success?: boolean;
            data?: components["schemas"]["DailyMetricResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        DailyMetricResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sellerId?: number;
            /** Format: date */
            metricDate?: string;
            /** Format: int32 */
            orderCount?: number;
            salesAmount?: number;
            averageOrderAmount?: number;
            /** Format: int32 */
            soldOutProductCount?: number;
            /** Format: int32 */
            staleProductCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseSellerAccessTokenResponse: {
            success?: boolean;
            data?: components["schemas"]["SellerAccessTokenResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        SellerAccessTokenResponse: {
            /** Format: int64 */
            sellerId?: number;
            accountId?: string;
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        ApiResponseSampleDataBootstrapResponse: {
            success?: boolean;
            data?: components["schemas"]["SampleDataBootstrapResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        SampleDataBootstrapResponse: {
            scenario?: string;
            /** Format: date */
            previousMetricDate?: string;
            /** Format: date */
            targetMetricDate?: string;
            /** Format: int32 */
            sellerCount?: number;
            /** Format: int32 */
            productCount?: number;
            /** Format: int32 */
            orderCount?: number;
            /** Format: int32 */
            orderItemCount?: number;
            sellers?: components["schemas"]["SampleDataSellerResponse"][];
        };
        SampleDataSellerResponse: {
            /** Format: int64 */
            sellerId?: number;
            externalSellerId?: string;
            sellerName?: string;
            /** Format: int32 */
            productCount?: number;
            /** Format: int32 */
            orderCount?: number;
        };
        ApiResponseDailyPipelineRunResponse: {
            success?: boolean;
            data?: components["schemas"]["DailyPipelineRunResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        DailyPipelineRunResponse: {
            /** Format: int64 */
            runId?: number;
            /** @enum {string} */
            pipelineType?: "DAILY";
            /** @enum {string} */
            triggerType?: "MANUAL" | "SCHEDULED";
            /** @enum {string} */
            status?: "RUNNING" | "SUCCESS" | "PARTIAL_SUCCESS" | "FAILED";
            /** Format: date */
            metricDate?: string;
            /** Format: int32 */
            totalSellerCount?: number;
            /** Format: int32 */
            processedSellerCount?: number;
            /** Format: int32 */
            failedSellerCount?: number;
            /** Format: int32 */
            generatedInsightCount?: number;
            failedSellerIds?: number[];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: int64 */
            durationMs?: number;
        };
        ApiResponseInsightResponse: {
            success?: boolean;
            data?: components["schemas"]["InsightResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        ApiResponseDashboardResponse: {
            success?: boolean;
            data?: components["schemas"]["DashboardResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        DashboardInsightSummaryResponse: {
            /** Format: int64 */
            totalCount?: number;
            /** Format: int64 */
            lowCount?: number;
            /** Format: int64 */
            mediumCount?: number;
            /** Format: int64 */
            highCount?: number;
        };
        DashboardMetricPointResponse: {
            /** Format: date */
            metricDate?: string;
            /** Format: int32 */
            orderCount?: number;
            salesAmount?: number;
            averageOrderAmount?: number;
            /** Format: int32 */
            soldOutProductCount?: number;
            /** Format: int32 */
            staleProductCount?: number;
        };
        DashboardResponse: {
            /** Format: int64 */
            sellerId?: number;
            sellerName?: string;
            /** Format: date */
            latestMetricDate?: string;
            latestMetric?: components["schemas"]["DailyMetricResponse"];
            /** Format: int32 */
            metricTrendDays?: number;
            metricTrend?: components["schemas"]["DashboardMetricPointResponse"][];
            insightSummary?: components["schemas"]["DashboardInsightSummaryResponse"];
            /** Format: int32 */
            recentInsightCount?: number;
            recentInsights?: components["schemas"]["InsightResponse"][];
            latestPipelineStatus?: components["schemas"]["SellerPipelineStatusResponse"];
        };
        SellerPipelineStatusResponse: {
            /** Format: int64 */
            runId?: number;
            /** Format: date */
            metricDate?: string;
            /** @enum {string} */
            triggerType?: "MANUAL" | "SCHEDULED";
            /** @enum {string} */
            status?: "SUCCESS" | "FAILED";
            /** Format: int32 */
            generatedInsightCount?: number;
            errorMessage?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
        };
        ApiResponseDashboardMetricRangeResponse: {
            success?: boolean;
            data?: components["schemas"]["DashboardMetricRangeResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        DashboardMetricRangeResponse: {
            /** Format: int64 */
            sellerId?: number;
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            /** Format: int32 */
            metricCount?: number;
            metrics?: components["schemas"]["DashboardMetricPointResponse"][];
        };
        ApiResponseRecentInsightsResponse: {
            success?: boolean;
            data?: components["schemas"]["RecentInsightsResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        RecentInsightsResponse: {
            /** Format: int64 */
            sellerId?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int32 */
            insightCount?: number;
            insights?: components["schemas"]["InsightResponse"][];
        };
        ApiResponseHealthCheckResponse: {
            success?: boolean;
            data?: components["schemas"]["HealthCheckResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        HealthCheckResponse: {
            application?: string;
            status?: string;
            database?: string;
            activeProfiles?: string[];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListPipelineRunSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["PipelineRunSummaryResponse"][];
            error?: components["schemas"]["ErrorResponse"];
        };
        PipelineRunSummaryResponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            pipelineType?: "DAILY";
            /** @enum {string} */
            triggerType?: "MANUAL" | "SCHEDULED";
            /** @enum {string} */
            status?: "RUNNING" | "SUCCESS" | "PARTIAL_SUCCESS" | "FAILED";
            /** Format: date */
            metricDate?: string;
            /** Format: int32 */
            totalSellerCount?: number;
            /** Format: int32 */
            processedSellerCount?: number;
            /** Format: int32 */
            failedSellerCount?: number;
            /** Format: int32 */
            generatedInsightCount?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: int64 */
            durationMs?: number;
        };
        ApiResponsePipelineRunDetailResponse: {
            success?: boolean;
            data?: components["schemas"]["PipelineRunDetailResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        PipelineRunDetailResponse: {
            run?: components["schemas"]["PipelineRunSummaryResponse"];
            /** Format: int32 */
            itemCount?: number;
            items?: components["schemas"]["PipelineRunItemResponse"][];
        };
        PipelineRunItemResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sellerId?: number;
            /** @enum {string} */
            status?: "SUCCESS" | "FAILED";
            /** Format: int32 */
            generatedInsightCount?: number;
            errorMessage?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: int64 */
            durationMs?: number;
        };
        ApiResponsePipelineExecutionLockReleaseResponse: {
            success?: boolean;
            data?: components["schemas"]["PipelineExecutionLockReleaseResponse"];
            error?: components["schemas"]["ErrorResponse"];
        };
        PipelineExecutionLockReleaseResponse: {
            /** Format: date */
            metricDate?: string;
            released?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSellerCredentialResponse"];
                };
            };
        };
    };
    upsert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertSellerCredentialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSellerCredentialResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSellerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSellerResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInsightsByDateResponse"];
                };
            };
        };
    };
    importOrdersCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportJobResponse"];
                };
            };
        };
    };
    aggregate: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDailyMetricResponse"];
                };
            };
        };
    };
    issueSellerToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSellerAccessTokenResponse"];
                };
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: {
                scenario?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSampleDataBootstrapResponse"];
                };
            };
        };
    };
    runDailyPipeline: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDailyPipelineRunResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSellerResponse"];
                };
            };
        };
    };
    getByDate: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInsightsByDateResponse"];
                };
            };
        };
    };
    getInsight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
                insightId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInsightResponse"];
                };
            };
        };
    };
    getImportJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
                importJobId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportJobResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                metricDays?: number;
                insightLimit?: number;
            };
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDashboardResponse"];
                };
            };
        };
    };
    getMetricRange: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDashboardMetricRangeResponse"];
                };
            };
        };
    };
    getRecentInsights: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                sellerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRecentInsightsResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sellerId: number;
                metricDate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDailyMetricResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseHealthCheckResponse"];
                };
            };
        };
    };
    getRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPipelineRunSummaryResponse"];
                };
            };
        };
    };
    getRunDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePipelineRunDetailResponse"];
                };
            };
        };
    };
    forceReleaseLock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                metricDate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePipelineExecutionLockReleaseResponse"];
                };
            };
        };
    };
}
